name: Lint Application

on:
  push:
    branches: ['*', '*/*', '**']
  pull_request:
    branches: ['*', '*/*', '**']
  workflow_dispatch:

jobs:
  lint-frontend:
    name: Lint Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (frontend)
        run: npm ci
        working-directory: ./frontend

      - name: Run lint (frontend)
        run: npm run lint
        working-directory: ./frontend

  lint-backend:
    name: Lint Backend (Node.js)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (backend)
        run: npm ci
        working-directory: ./back-end

      - name: Run lint (backend)
        run: npm run lint
        working-directory: ./back-end